# Generated by Django 4.1.3 on 2023-02-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dubaivisarequest_alter_feedbackrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubaivisarequest',
            name='passport_closure_date',
            field=models.DateField(),
        ),
    ]
