# Generated by Django 4.1.3 on 2023-02-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_dubaivisarequest_passport_closure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dubaivisarequest',
            name='visa_duration',
            field=models.CharField(choices=[('one month', 'One month'), ('two months', 'Two months'), ('resident visa', 'Resident visa'), ('Mu', '')], default='One month', max_length=120),
        ),
    ]
