# Generated by Django 4.1.3 on 2023-02-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dubaivisarequest_visa_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dubaivisarequest',
            old_name='passpost_series',
            new_name='passport_series',
        ),
    ]
